/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DraftsRouteImport } from './routes/drafts'
import { Route as ExtensionRouteImport } from './routes/extension'
import { Route as ImportJobRouteImport } from './routes/import-job'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppApplicationsRouteImport } from './routes/app/applications'
import { Route as AppEditorRouteImport } from './routes/app/editor'
import { Route as AppExtensionRouteImport } from './routes/app/extension'
import { Route as AppTemplatesRouteImport } from './routes/app/templates'
import { Route as AppToolkitRouteImport } from './routes/app/toolkit'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ResourcesIndexRouteImport } from './routes/resources/index'
import { Route as ResourcesSlugRouteImport } from './routes/resources/$slug'
import { Route as SettingsAiRouteImport } from './routes/settings.ai'
import { Route as ToolkitIndexRouteImport } from './routes/toolkit/index'
import { Route as ToolkitBulletAnalyzerRouteImport } from './routes/toolkit/bullet-analyzer'
import { Route as ToolkitPdfTextPreviewRouteImport } from './routes/toolkit/pdf-text-preview'
import { Route as AppBlogIndexRouteImport } from './routes/app/blog/index'
import { Route as AppBlogSlugRouteImport } from './routes/app/blog/$slug'
import { Route as AppSettingsAiRouteImport } from './routes/app/settings.ai'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftsRoute = DraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionRoute = ExtensionRouteImport.update({
  id: '/extension',
  path: '/extension',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportJobRoute = ImportJobRouteImport.update({
  id: '/import-job',
  path: '/import-job',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppApplicationsRoute = AppApplicationsRouteImport.update({
  id: '/app/applications',
  path: '/app/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEditorRoute = AppEditorRouteImport.update({
  id: '/app/editor',
  path: '/app/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const AppExtensionRoute = AppExtensionRouteImport.update({
  id: '/app/extension',
  path: '/app/extension',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/app/templates',
  path: '/app/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const AppToolkitRoute = AppToolkitRouteImport.update({
  id: '/app/toolkit',
  path: '/app/toolkit',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/resources/$slug',
  path: '/resources/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAiRoute = SettingsAiRouteImport.update({
  id: '/settings/ai',
  path: '/settings/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolkitIndexRoute = ToolkitIndexRouteImport.update({
  id: '/toolkit/',
  path: '/toolkit/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolkitBulletAnalyzerRoute = ToolkitBulletAnalyzerRouteImport.update({
  id: '/toolkit/bullet-analyzer',
  path: '/toolkit/bullet-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolkitPdfTextPreviewRoute = ToolkitPdfTextPreviewRouteImport.update({
  id: '/toolkit/pdf-text-preview',
  path: '/toolkit/pdf-text-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBlogIndexRoute = AppBlogIndexRouteImport.update({
  id: '/app/blog/',
  path: '/app/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBlogSlugRoute = AppBlogSlugRouteImport.update({
  id: '/app/blog/$slug',
  path: '/app/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsAiRoute = AppSettingsAiRouteImport.update({
  id: '/app/settings/ai',
  path: '/app/settings/ai',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/drafts': typeof DraftsRoute
  '/extension': typeof ExtensionRoute
  '/import-job': typeof ImportJobRoute
  '/templates': typeof TemplatesRoute
  '/app/applications': typeof AppApplicationsRoute
  '/app/editor': typeof AppEditorRoute
  '/app/extension': typeof AppExtensionRoute
  '/app/templates': typeof AppTemplatesRoute
  '/app/toolkit': typeof AppToolkitRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/settings/ai': typeof SettingsAiRoute
  '/toolkit/bullet-analyzer': typeof ToolkitBulletAnalyzerRoute
  '/toolkit/pdf-text-preview': typeof ToolkitPdfTextPreviewRoute
  '/app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/toolkit/': typeof ToolkitIndexRoute
  '/app/blog/$slug': typeof AppBlogSlugRoute
  '/app/settings/ai': typeof AppSettingsAiRoute
  '/app/blog/': typeof AppBlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/drafts': typeof DraftsRoute
  '/extension': typeof ExtensionRoute
  '/import-job': typeof ImportJobRoute
  '/templates': typeof TemplatesRoute
  '/app/applications': typeof AppApplicationsRoute
  '/app/editor': typeof AppEditorRoute
  '/app/extension': typeof AppExtensionRoute
  '/app/templates': typeof AppTemplatesRoute
  '/app/toolkit': typeof AppToolkitRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/settings/ai': typeof SettingsAiRoute
  '/toolkit/bullet-analyzer': typeof ToolkitBulletAnalyzerRoute
  '/toolkit/pdf-text-preview': typeof ToolkitPdfTextPreviewRoute
  '/app': typeof AppIndexRoute
  '/blog': typeof BlogIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/toolkit': typeof ToolkitIndexRoute
  '/app/blog/$slug': typeof AppBlogSlugRoute
  '/app/settings/ai': typeof AppSettingsAiRoute
  '/app/blog': typeof AppBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/drafts': typeof DraftsRoute
  '/extension': typeof ExtensionRoute
  '/import-job': typeof ImportJobRoute
  '/templates': typeof TemplatesRoute
  '/app/applications': typeof AppApplicationsRoute
  '/app/editor': typeof AppEditorRoute
  '/app/extension': typeof AppExtensionRoute
  '/app/templates': typeof AppTemplatesRoute
  '/app/toolkit': typeof AppToolkitRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/settings/ai': typeof SettingsAiRoute
  '/toolkit/bullet-analyzer': typeof ToolkitBulletAnalyzerRoute
  '/toolkit/pdf-text-preview': typeof ToolkitPdfTextPreviewRoute
  '/app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/toolkit/': typeof ToolkitIndexRoute
  '/app/blog/$slug': typeof AppBlogSlugRoute
  '/app/settings/ai': typeof AppSettingsAiRoute
  '/app/blog/': typeof AppBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/drafts'
    | '/extension'
    | '/import-job'
    | '/templates'
    | '/app/applications'
    | '/app/editor'
    | '/app/extension'
    | '/app/templates'
    | '/app/toolkit'
    | '/blog/$slug'
    | '/resources/$slug'
    | '/settings/ai'
    | '/toolkit/bullet-analyzer'
    | '/toolkit/pdf-text-preview'
    | '/app/'
    | '/blog/'
    | '/resources/'
    | '/toolkit/'
    | '/app/blog/$slug'
    | '/app/settings/ai'
    | '/app/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/drafts'
    | '/extension'
    | '/import-job'
    | '/templates'
    | '/app/applications'
    | '/app/editor'
    | '/app/extension'
    | '/app/templates'
    | '/app/toolkit'
    | '/blog/$slug'
    | '/resources/$slug'
    | '/settings/ai'
    | '/toolkit/bullet-analyzer'
    | '/toolkit/pdf-text-preview'
    | '/app'
    | '/blog'
    | '/resources'
    | '/toolkit'
    | '/app/blog/$slug'
    | '/app/settings/ai'
    | '/app/blog'
  id:
    | '__root__'
    | '/'
    | '/drafts'
    | '/extension'
    | '/import-job'
    | '/templates'
    | '/app/applications'
    | '/app/editor'
    | '/app/extension'
    | '/app/templates'
    | '/app/toolkit'
    | '/blog/$slug'
    | '/resources/$slug'
    | '/settings/ai'
    | '/toolkit/bullet-analyzer'
    | '/toolkit/pdf-text-preview'
    | '/app/'
    | '/blog/'
    | '/resources/'
    | '/toolkit/'
    | '/app/blog/$slug'
    | '/app/settings/ai'
    | '/app/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DraftsRoute: typeof DraftsRoute
  ExtensionRoute: typeof ExtensionRoute
  ImportJobRoute: typeof ImportJobRoute
  TemplatesRoute: typeof TemplatesRoute
  AppApplicationsRoute: typeof AppApplicationsRoute
  AppEditorRoute: typeof AppEditorRoute
  AppExtensionRoute: typeof AppExtensionRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppToolkitRoute: typeof AppToolkitRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ResourcesSlugRoute: typeof ResourcesSlugRoute
  SettingsAiRoute: typeof SettingsAiRoute
  ToolkitBulletAnalyzerRoute: typeof ToolkitBulletAnalyzerRoute
  ToolkitPdfTextPreviewRoute: typeof ToolkitPdfTextPreviewRoute
  AppIndexRoute: typeof AppIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  ToolkitIndexRoute: typeof ToolkitIndexRoute
  AppBlogSlugRoute: typeof AppBlogSlugRoute
  AppSettingsAiRoute: typeof AppSettingsAiRoute
  AppBlogIndexRoute: typeof AppBlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drafts': {
      id: '/drafts'
      path: '/drafts'
      fullPath: '/drafts'
      preLoaderRoute: typeof DraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extension': {
      id: '/extension'
      path: '/extension'
      fullPath: '/extension'
      preLoaderRoute: typeof ExtensionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-job': {
      id: '/import-job'
      path: '/import-job'
      fullPath: '/import-job'
      preLoaderRoute: typeof ImportJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/applications': {
      id: '/app/applications'
      path: '/app/applications'
      fullPath: '/app/applications'
      preLoaderRoute: typeof AppApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/editor': {
      id: '/app/editor'
      path: '/app/editor'
      fullPath: '/app/editor'
      preLoaderRoute: typeof AppEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/extension': {
      id: '/app/extension'
      path: '/app/extension'
      fullPath: '/app/extension'
      preLoaderRoute: typeof AppExtensionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/templates': {
      id: '/app/templates'
      path: '/app/templates'
      fullPath: '/app/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/toolkit': {
      id: '/app/toolkit'
      path: '/app/toolkit'
      fullPath: '/app/toolkit'
      preLoaderRoute: typeof AppToolkitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/resources/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/ai': {
      id: '/settings/ai'
      path: '/settings/ai'
      fullPath: '/settings/ai'
      preLoaderRoute: typeof SettingsAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toolkit/': {
      id: '/toolkit/'
      path: '/toolkit'
      fullPath: '/toolkit/'
      preLoaderRoute: typeof ToolkitIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toolkit/bullet-analyzer': {
      id: '/toolkit/bullet-analyzer'
      path: '/toolkit/bullet-analyzer'
      fullPath: '/toolkit/bullet-analyzer'
      preLoaderRoute: typeof ToolkitBulletAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toolkit/pdf-text-preview': {
      id: '/toolkit/pdf-text-preview'
      path: '/toolkit/pdf-text-preview'
      fullPath: '/toolkit/pdf-text-preview'
      preLoaderRoute: typeof ToolkitPdfTextPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/blog/': {
      id: '/app/blog/'
      path: '/app/blog'
      fullPath: '/app/blog/'
      preLoaderRoute: typeof AppBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/blog/$slug': {
      id: '/app/blog/$slug'
      path: '/app/blog/$slug'
      fullPath: '/app/blog/$slug'
      preLoaderRoute: typeof AppBlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings/ai': {
      id: '/app/settings/ai'
      path: '/app/settings/ai'
      fullPath: '/app/settings/ai'
      preLoaderRoute: typeof AppSettingsAiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DraftsRoute: DraftsRoute,
  ExtensionRoute: ExtensionRoute,
  ImportJobRoute: ImportJobRoute,
  TemplatesRoute: TemplatesRoute,
  AppApplicationsRoute: AppApplicationsRoute,
  AppEditorRoute: AppEditorRoute,
  AppExtensionRoute: AppExtensionRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppToolkitRoute: AppToolkitRoute,
  BlogSlugRoute: BlogSlugRoute,
  ResourcesSlugRoute: ResourcesSlugRoute,
  SettingsAiRoute: SettingsAiRoute,
  ToolkitBulletAnalyzerRoute: ToolkitBulletAnalyzerRoute,
  ToolkitPdfTextPreviewRoute: ToolkitPdfTextPreviewRoute,
  AppIndexRoute: AppIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  ToolkitIndexRoute: ToolkitIndexRoute,
  AppBlogSlugRoute: AppBlogSlugRoute,
  AppSettingsAiRoute: AppSettingsAiRoute,
  AppBlogIndexRoute: AppBlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
