import { createFileRoute, Link } from "@tanstack/react-router";
import { PageLayout } from "../../components/PageLayout";
export const Route = createFileRoute("/app/design-lab")({ component: DesignResearch });
function DesignResearch() {
  return <PageLayout variant="fixed" title="Design research" description="A simpler workspace, built around getting an application ready.">
    <section className="research-direction"><div><span className="research-label">CURRENT DIRECTION</span><h2>Less interface.<br />More forward motion.</h2><p>Readable text, direct actions, and room to think. Your CV appears when you’re ready to work on it. Suggestions show their changes and leave the decision with you.</p><Link to="/app" className="product-start-link">Try the current workspace ↗</Link></div><ol><li><strong>Start with your experience</strong><p>Upload a CV or create one without an extra questionnaire.</p></li><li><strong>Work on one thing at a time</strong><p>Edit your details and experience. Open design controls or a preview when you need them.</p></li><li><strong>Know what you’re keeping</strong><p>Clear saved states, explicit AI decisions, and a reusable profile.</p></li></ol></section>
    <section className="research-evidence"><h2>What informed the changes</h2><p>This is desk research and design interpretation, not a substitute for testing with applicants.</p><ul><li><a href="https://news.linkedin.com/2026/LinkedIn-Research-Talent-2026" target="_blank" rel="noreferrer">LinkedIn’s 2026 applicant research ↗</a><p>Job seekers report feeling unprepared. The workspace should reduce uncertainty and show a useful next action.</p></li><li><a href="https://www.nngroup.com/articles/progressive-disclosure/" target="_blank" rel="noreferrer">Progressive disclosure, Nielsen Norman Group ↗</a><p>Keep frequent tasks visible. Reveal advanced formatting and setup only when needed.</p></li><li><a href="https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum" target="_blank" rel="noreferrer">Readable contrast, W3C ↗</a><p>Use at least 4.5:1 contrast for ordinary text. Check actual screens, not just colour swatches.</p></li></ul></section>
    <details className="research-archive"><summary>Earlier concepts & local A/B/C study · Round 2 archive</summary><p>Neutral, Blueprint and Signal are earlier prototypes. They do not represent the current design. Their study remains separate so earlier results cannot be mistaken for evidence about the new workspace.</p><div className="research-archive-links">{["neutral", "blueprint", "signal"].map(name => <a key={name} href={`/design-options/${name}.html`}>Open {name} prototype ↗</a>)}</div><a href="/design-options/test.html?view=results">Review or export Round 2 results ↗</a></details>
  </PageLayout>;
}
